version: '3.8'

services:

  backend:
    build: .
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0.0.0.0:8000 --workers 8 bitpin.wsgi:application --log-level debug
      "
    volumes:
      - .:/code
      - ./staticfiles:/blog/staticfiles
    env_file:
      - .env
    network_mode: host

  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./staticfiles:/static
    depends_on:
      - backend



